### ISSUE TITLE
添加经纬度 需要用户端和司机端相关接口的调整

### ISSUE THREAD

**Issue by gliubc** [gliubc/test#16]

**Comment by alice1994tw** [comment]
1.
create_order
![image](https://user-images.githubusercontent.com/23089910/50679414-3386cd80-103e-11e9-82c8-4d6b04992c18.png)
新增dep_lat、dep_long、arr_lat、arr_long

2.
driver_today_order
![image](https://user-images.githubusercontent.com/23089910/50679668-61b8dd00-103f-11e9-9583-08d0335755d4.png)
新增dep_lat、dep_long

3.
driver_order_detail
![image](https://user-images.githubusercontent.com/23089910/50679690-79906100-103f-11e9-8c78-c0acdd5c1c19.png)
新增dep_lat、dep_long、arr_lat、arr_long

**Comment by DinfotechYOYO** [comment]
@gliubc 目前我们检查经纬度相关影响接口如上，并修改完毕，
再请确认看看是否有问题，谢谢

**Comment by gliubc** [comment]
获取最近回诊单、最近医院、住家地址的接口，都需要返回经纬度信息

**Comment by gliubc** [comment]
个人资料保存用户居住地址、常去医院的接口需要存储经纬度信息

**Comment by alice1994tw** [comment]
修改個案資料 => member_upd
取得地圖資料 => get_map_address
已修正
