### ISSUE TITLE
修改订单可编辑的栏位定义

### ISSUE THREAD

**Issue by gliubc** [gliubc/test#17]

**Comment by DinfotechYOYO** [comment]
线上预约型态修改订单，可编辑栏位如下红框中，并且按钮应为"完成修改"：
![image](https://user-images.githubusercontent.com/46367887/50678830-88751480-103b-11e9-9208-765cc5c6a968.png)
![image](https://user-images.githubusercontent.com/46367887/50678844-9a56b780-103b-11e9-9a21-73b9e431edeb.png)

**Comment by DinfotechYOYO** [comment]
@gliubc 是的，不可修改接驳类型，回诊单可编辑栏位如下红框：
![image](https://user-images.githubusercontent.com/46367887/50680463-c1fd4e00-1042-11e9-8e0c-10cc7ddcfb50.png)
