### ISSUE TITLE
再次确认一下个人资料的姓名能不能修改？

### ISSUE THREAD

**Issue by gliubc** [gliubc/test#2]
之前说过一次姓名和身份证和生日都是不可修改的

**Comment by DinfotechYOYO** [comment]
是的，不可修改的

**Comment by gliubc** [comment]
这个姓名一开始我们也是按要求做成了不可修改，
后来发现用户没有添加姓名的地方，就改成可修改的了。
解释一下我们的疑问，再次确认是否可修改？

**Comment by DinfotechYOYO** [comment]
确认为不可修改，但注册时添加一个姓名必填栏位，并且后续app代入用户姓名时，统一由api传数据库的姓名带入
