### ISSUE TITLE
通知中心页面下方的确认上车 时间延误流程需要再次确认流程

### ISSUE THREAD

**Issue by gliubc** [gliubc/test#5]

**Comment by alice1994tw** [comment]
1.
![image](https://user-images.githubusercontent.com/23089910/50675327-63c37180-1028-11e9-88a1-3dd4884efaa8.png)

get_all_notification 這隻api 回傳多一個Type
當Type為"APP",如下圖
![image](https://user-images.githubusercontent.com/23089910/50675364-9d947800-1028-11e9-8b37-9a51b73e5d18.png)
當Type為"USER",如下圖
![image](https://user-images.githubusercontent.com/23089910/50675383-c0269100-1028-11e9-94cc-e676d618d490.png)

**Comment by alice1994tw** [comment]
2.
時間延誤
![image](https://user-images.githubusercontent.com/23089910/50675682-8f475b80-102a-11e9-81f7-787d9fa7779d.png)

**Comment by alice1994tw** [comment]
3.
確認上車
![image](https://user-images.githubusercontent.com/23089910/50675701-aa19d000-102a-11e9-93e5-df1075186646.png)

4.
回傳訊息
![image](https://user-images.githubusercontent.com/23089910/50675715-bb62dc80-102a-11e9-99bf-ad12caaa4396.png)

5.
取消訂單
![image](https://user-images.githubusercontent.com/23089910/50675720-c87fcb80-102a-11e9-9f54-15a784bdb4a4.png)
